<?php

// This is an autogenerated file - do not edit!

// @codeCoverageIgnoreStart
spl_autoload_register(
    function($class)
    {
        static $classes = array(
            ___CLASSLIST___
       );
       $cn = strtolower($class);
       if (isset($classes[$cn])) {
        require ___BASEDIR___$classes[$cn];
       }
    }
);
// @codeCoverageIgnoreEnd
